# Generated by Django 2.1.3 on 2019-08-05 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_register_date', models.DateTimeField(auto_now=True)),
                ('customer_got_info', models.CharField(choices=[('1', 'Написал мне'), ('2', 'От меня'), ('3', 'Увидел моё объявление')], max_length=1)),
                ('customer_surname', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_patronymic', models.CharField(max_length=100)),
                ('customer_form_academy', models.CharField(max_length=100)),
                ('customer_about_comments', models.TextField(max_length=100)),
                ('customer_contact_fact_academy', models.CharField(choices=[('Нет', 'Не связался'), ('Да', 'Связался')], max_length=20, null=True)),
                ('customer_contract_fact', models.CharField(choices=[('Нет', 'Не подписал'), ('Да', 'Подписал')], max_length=20, null=True)),
                ('customer_payment_fact_when', models.CharField(max_length=100, null=True)),
                ('customer_payment_fact_where', models.CharField(max_length=100, null=True)),
                ('customer_payment_fact_how_much', models.CharField(max_length=100, null=True)),
                ('customer_partner', models.ForeignKey(default=-1, on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=200)),
                ('message_date', models.DateTimeField(auto_now=True)),
                ('message_from', models.ForeignKey(default=-1, limit_choices_to={'groups__name': 'partners'}, on_delete='', related_name='send_letter', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('message_to', models.ForeignKey(default=-1, limit_choices_to={'groups__name': 'managers'}, on_delete='', related_name='got_letter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_surname', models.CharField(max_length=100, verbose_name='')),
                ('partner_name', models.CharField(max_length=100, verbose_name='')),
                ('partner_patronymic', models.CharField(max_length=100, verbose_name='')),
                ('partner_email', models.EmailField(max_length=100, verbose_name='')),
                ('partner_number', models.BigIntegerField(verbose_name='')),
                ('partner_free_info', models.TextField(verbose_name='')),
                ('partner_user', models.ForeignKey(default=-1, on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner',
            },
        ),
    ]
