# Generated by Django 2.1.3 on 2019-08-07 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20190807_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=200)),
                ('message_date', models.DateTimeField(auto_now=True)),
                ('message_from', models.ForeignKey(default=-1, limit_choices_to={'groups__name': 'managers'}, on_delete='', related_name='send_letter_manager', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('message_to', models.ForeignKey(default=-1, limit_choices_to={'groups__name': 'uppermanagers'}, on_delete='', related_name='got_letter_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_manager',
            },
        ),
    ]
