# Generated by Django 2.1.3 on 2019-08-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_message_uppermanager_partner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message_uppermanager_partner',
            table='message_uppermanager_partner',
        ),
    ]
