# Generated by Django 2.1.3 on 2019-08-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190807_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_uppermanager_partner',
            name='message_from',
        ),
        migrations.RemoveField(
            model_name='message_uppermanager_partner',
            name='message_to',
        ),
        migrations.DeleteModel(
            name='Message_uppermanager_partner',
        ),
    ]
