# Generated by Django 2.1.3 on 2019-08-07 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_auto_20190807_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_from_back',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'uppermanagers'}, null=True, on_delete='', related_name='send_letter_back', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='message',
            name='message_to_back',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'partners'}, null=True, on_delete='', related_name='got_letter_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message_manager',
            name='message_from_back',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'uppermanagers'}, null=True, on_delete='', related_name='send_letter_manager_back', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AddField(
            model_name='message_manager',
            name='message_to_back',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'partners'}, null=True, on_delete='', related_name='got_letter_manager_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'partners'}, null=True, on_delete='', related_name='send_letter', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'uppermanagers'}, null=True, on_delete='', related_name='got_letter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message_manager',
            name='message_from',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'partners'}, null=True, on_delete='', related_name='send_letter_manager', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='message_manager',
            name='message_to',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'uppermanagers'}, null=True, on_delete='', related_name='got_letter_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
