# Generated by Django 2.1.3 on 2019-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190809_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_contract_fact',
            field=models.CharField(default='Нет', max_length=20, null=True),
        ),
    ]
