# Generated by Django 2.1.3 on 2019-08-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190809_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_contact_fact_academy',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_contract_fact',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_payment_fact_how_much',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_payment_fact_when',
            field=models.DateTimeField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_payment_fact_where',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
    ]
