# Generated by Django 2.1.3 on 2019-08-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20190809_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_payment_fact_how_much',
            field=models.IntegerField(max_length=100, null=True, verbose_name=''),
        ),
    ]
