# Generated by Django 2.1.3 on 2019-08-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20190809_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_payment_fact_when',
            field=models.DateField(null=True, verbose_name=''),
        ),
    ]
