# Generated by Django 2.1.3 on 2019-08-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20190809_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_got_info',
            field=models.CharField(choices=[('Написал мне', 'Написал мне'), ('От меня', 'От меня'), ('Увидел моё объявление', 'Увидел моё объявление')], max_length=1),
        ),
    ]
