# Generated by Django 2.1.3 on 2019-08-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20190810_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_got_info',
            field=models.CharField(choices=[('Написал мне', 'Написал мне'), ('От меня', 'От меня'), ('Увидел моё объявление', 'Увидел моё объявление')], max_length=20),
        ),
    ]
