# Generated by Django 2.1.3 on 2019-08-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20190810_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_register_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
