# Generated by Django 2.1.3 on 2019-08-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20190810_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_remove',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_about_comments',
            field=models.TextField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_form_academy',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_got_info',
            field=models.CharField(choices=[('Написал мне', 'Написал мне'), ('От меня', 'От меня'), ('По объявлению', 'По объявлению')], max_length=20, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_patronymic',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_surname',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
