# Generated by Django 2.1.3 on 2019-08-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20190811_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_status',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
    ]
