# Generated by Django 2.1.3 on 2019-08-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_partner_partner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'partners'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_letter', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
