# Generated by Django 2.1.3 on 2019-08-14 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20190814_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_partner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_from_back',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'uppermanagers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_letter_back', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'uppermanagers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='got_letter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_to_back',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'partners'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='got_letter_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message_manager',
            name='message_from',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'managers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_letter_manager', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='message_manager',
            name='message_from_back',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'uppermanagers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_letter_manager_back', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='message_manager',
            name='message_to',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'uppermanagers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='got_letter_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message_manager',
            name='message_to_back',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'managers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='got_letter_manager_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
